/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package webcrawler

import org.apache.commons.lang3.ObjectUtils
import org.jsoup.HttpStatusException
import org.jsoup.Jsoup
import com.opencsv.CSVWriter

class App {
    static void main(String[] args) {

        def URL = "https://go.olx.com.br/grande-goiania-e-anapolis?q=iphone%2011&sp=2"
        def URLSecondPage = "https://go.olx.com.br/grande-goiania-e-anapolis?o=2&q=iphone%2011&sp=2"
        def URLThirdPage = "https://go.olx.com.br/grande-goiania-e-anapolis?o=3&q=iphone%2011&sp=2"

        def doc1 = Jsoup.connect(URL).get()
        def list1 = doc1.getElementById("ad-list")
        def itemLinkList = list1.getElementsByClass("fnmrjs-0 fyjObc")

        def doc2 = Jsoup.connect(URLSecondPage).get()
        def list2 = doc2.getElementById("ad-list")
        itemLinkList.addAll(list2.getElementsByClass("fnmrjs-0 fyjObc"))

        def doc3 = Jsoup.connect(URLThirdPage).get()
        def list3 = doc3.getElementById("ad-list")
        itemLinkList.addAll(list3.getElementsByClass("fnmrjs-0 fyjObc"))

        ArrayList<Anuncio> listAnuncios = new ArrayList<Anuncio>()
        ArrayList<Integer> listValores = new ArrayList<Integer>()

        for(def item : itemLinkList) {
            try {
                def anuncioURL =  item.attr("href")
                def anuncioDoc = Jsoup.connect(anuncioURL)
                        .userAgent("Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0")
                        .referrer("https://www.google.com")
                        .get()

                def titulo = anuncioDoc.select('h1').first().text()
                def valor = anuncioDoc.select('h2.sc-1wimjbb-2').first().text()
                def endereco = anuncioDoc.select('dd.sc-1f2ug0x-1.ljYeKO.sc-ifAKCX.kaNiaQ')
                println(endereco)

                def cep
                if (endereco[0]) {
                    cep = endereco[0].text()
                } else {
                    cep = ""
                }

                def municipio
                if (endereco[1]) {
                    municipio = endereco[1].text()
                } else {
                    municipio = ""
                }

                def bairro
                if (endereco[2]) {
                    bairro = endereco[2].text()
                } else {
                    bairro = ""
                }


                def anuncio = new Anuncio(titulo, valor.replaceAll("\\D", "") as Integer, cep, municipio, bairro, anuncioURL)

                listAnuncios.add(anuncio)
                listValores.add(valor.replaceAll("\\D", "") as Integer)
            } catch(HttpStatusException e) {

            } catch(SocketTimeoutException e) {

            }

        }

        def valorMedio = listValores.average()
        listAnuncios.removeAll {it.valor > valorMedio}

        new File("produtos.csv").withWriter {fileWriter ->
            def csvFileWriter = new CSVWriter(fileWriter)
            def headerList = ["titulo", "valor", "CEP", "municipio", "bairro", "url"]
            csvFileWriter.writeNext(headerList as String[], false)
            for(def anuncio : listAnuncios) {
                String[] nextLine = [anuncio.titulo, anuncio.valor as String, anuncio.cep, anuncio.municipio, anuncio.bairro, anuncio.URL]
                csvFileWriter.writeNext(nextLine, false)
            }
        }



    }
}
